import Head from 'next/head';

type Props = { title?: string; description?: string; image?: string };
export default function MetaTags({ title, description, image }: Props) {
	return (
		<Head>
			<title>{title ? `LIGMA | ${title}` : 'LIGMA'}</title>
			<meta name='twitter:card' content='summery' />
			<meta name='twitter:title' content={title} />
			<meta name='twitter:description' content={description} />
			<meta name='twitter:image' content={image} />

			<meta property='og:title' content={title} />
			<meta property='og:description' content={description} />
			<meta property='og:image' content={image} />

			<meta name='description' content='Generated by create next app' />
			<meta name='viewport' content='width=device-width, initial-scale=1' />
			<link rel='icon' href='/favicon.ico' />
		</Head>
	);
}
